spring.application.name=personal-portfolio
spring.datasource.url=jdbc:postgresql://localhost:5432/portfoliodb
spring.datasource.username=postgres
spring.datasource.password=Sten1@postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always